# Wrangler configuration file
# For more details: https://developers.cloudflare.com/workers/wrangler/configuration/

name = "googleapi"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "gmail_manager"
database_id = "2d03b6de-d153-4f64-a607-9e35f0a8e55b"

[assets]
directory = "./public"
binding = "ASSETS"

[env.production]
[env.production.vars]
REDIRECT_URI = "https://google.devappnow.com/auth/google/callback"
